# Generated by Django 5.1.1 on 2024-10-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_subcategory_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thum_img',
        ),
    ]
