# Generated by Django 5.1.1 on 2024-10-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_subcategory_remove_product_thum_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_reviews',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
