# Generated by Django 5.1.1 on 2024-10-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveBigIntegerField(blank=True, null=True)),
                ('heading', models.CharField(blank=True, help_text='Heading of the slide', max_length=200)),
                ('image', models.ImageField(help_text='Image for the slide', upload_to='slider_images/')),
                ('short_desc', models.TextField(blank=True, help_text='Description for the slide')),
                ('btn_txt', models.CharField(blank=True, help_text='Text for the button', max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='URL the button will link to')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
